import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export default function Home({ data }) {
  const [formData, setFormData] = useState({})
  const [movies, setMovies] = useState(data)

  async function saveMovie(e) {
    e.preventDefault()
    setMovies([ ...movies, formData ])
    const response = await fetch('/api/movies', {
      method: 'POST',
      body: JSON.stringify(formData)
    })
    return  await response.json()
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Movie List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {movies.map(item => {
            return (
              <li key={item.id}>
                <span>{item.title}</span>
                <span>{item.year}</span>
                <span>{item.description}</span>
                <Link href={`/movies/${item.slug}`}>
                  <a>More About this Movie</a>
                </Link>
              </li>
            )
          })}
        </ul>

        <form onSubmit={saveMovie}>
          <input type="text" placeholder="Title" name="title" onChange={e => setFormData({ ...formData, title: e.target.value })} />
          <input type="text" placeholder="Year" name="year" onChange={e => setFormData({ ...formData, year: +e.target.value })} />
          <textarea name="description" placeholder="Description" cols="50" rows="10" onChange={e => setFormData({ ...formData, description: e.target.value })} />
          <input type="text" placeholder="Slug" name="slug" onChange={e => setFormData({ ...formData, slug: e.target.value })} />
          <button type="submit">Add Movie</button>
        </form>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const movies = await prisma.movie.findMany()
  return {
    props: {
      data: movies
    }
  }
}
